name: projeto_mb_teste
description: "Aplicativo MB LeilÃµes"
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  carousel_slider: ^4.2.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.0
  firebase_analytics: ^11.0.0
  firebase_messaging: ^15.0.0
  chewie: ^1.7.1
  video_player: ^2.8.3
  youtube_player_flutter: ^9.0.2







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    ios: true
    image_path: "assets/logo_app.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo_app.png
